### PR TITLE
Add syntax highlighting for code-blocks

### PR DESCRIPTION
**Pull request by DragonChen-TW**
## Description
Refer #2.
I put [Prism.js](https://prismjs.com/) into `tmpl.html` to enable the syntax-highlighter.

Trigger Prism's auto highlighting by adding the className `language-xxx` to any `<code>` elements.
The [supported languages are there](https://prismjs.com/#supported-languages).

## Methods of triggering

There are two methods for loading source code inside this repo.
### 1. Auto (most in tour and examples)
Example:
```html
<pre data-codesrc="/path/to/exampleFile.go"></pre>
```

The content of go files will be read and put into a `<code>` element. 
I put the extension name of the file into `<code>`'s className and triggered Prism to highlight it.
```js
# /scripts/script.js
                // add language syntax highlight from Prism.js
                var langtype = e.dataset['codesrc'].split('.').pop();
                code.className = 'language-' + langtype;
                Prism.highlightElement(code);
```

### 2. Manually
Example:
```html
<pre><code>package yourgamemobile

import (
    "github.com/hajimehoshi/ebiten/v2"
    "github.com/hajimehoshi/ebiten/v2/mobile"

    "github.com/yourname/yourgame"
)

# ...
</code></pre>
```

I have to manually put the `language-xxx` className to the element depending on its language type.

```html
<pre><code class="language-go">
# ...
</code></pre>
```

**For testing, I only update 4 pages in the first chapter "install" of documents.**

### CODE REVIEW

**Comment by hajimehoshi** [comment]
I'm afraid I don't plan to introduce a syntax highlighting.

**Comment by yrchen-tw** [comment]
Why not?
Highlighting can increase the readability and health of eye 😃 .

**Comment by hajimehoshi** [comment]
> Why not?
> Highlighting can increase the readability and health of eye 😃 .

This is just my preference.

**Comment by yrchen-tw** [comment]
I still recommend this feature to you.
How about using a toggle button to enable/disable this feature? (default is false).
The state of false/true could be stored in `localstorage`.

If not, you can just close this PR.

**Comment by hajimehoshi** [comment]
I understand the benefit but I prefer less color variations. Colors are involved in the branding direction so I have to be very careful to adopt new color schemes. I should have closed #2 earlier. Sorry for the confusion.

**Pull request closed without merging**
