### PR TITLE
Fix typo anbbd -> and

### PR DESCRIPTION
**Pull request by sionleroux**
Just spotted this while reading the recent blog posts.

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Thanks, could you update the `content` side and then `go generate`? Thanks,

**Comment by sionleroux** [comment]
Ah, I didn't realise this setup was so fancy, I'll do that when I'm at a computer again 👍

**Comment by hajimehoshi** [comment]
If you are busy, I can update it instead of you...

**Comment by sionleroux** [comment]
Only took a minute :)

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
