### PR TITLE
Fix wasmserve link in webassembly.html

### PR DESCRIPTION
**Pull request by jmingtan**

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Thanks. Could you update content/ side and then run go-generate?

**Comment by hajimehoshi** [comment]
Hi, I'll wait for your response until tomorrow. If you don't respond until then, I'll fix this on my side.

**Comment by jmingtan** [comment]
Thanks for the tip, I didn't realise how the documentation system worked! Should be fixed now.

**Comment by hajimehoshi** [comment]
Perfect. Thank you!

**Review by hajimehoshi — APPROVED** [review]

**Pull request merged**
