### PR TITLE
Remove outdated comment about Update func

### PR DESCRIPTION
**Pull request by kisunji**
I think this was a remnant from v1 docs!

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Thanks! Could you run `go generate` at the root directory so that `./docs` is also updated?

**Comment by kisunji** [comment]
> 
> 
> Thanks! Could you run `go generate` at the root directory so that `./docs` is also updated?

Ah yes, will do!

**Comment by hajimehoshi** [comment]
It looks like you are working at a non-latest commit. Please rebase or merge your change with master. Thanks

**Comment by kisunji** [comment]
Looks like running gen from my Windows OS is making generating \r\n characters. Will fix!

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
